server:
port: 8080

spring:
  datasource:
    username: username
    password: password
    url:
      jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: false

indexing-settings:
  sites:
    - url: http://www.playback.ru/
      name: PlayBack
    - url: http://radiomv.ru/
      name: RadioMV